### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by PovarRavop** [wilozyx/Classic-Mechanics#1]
Not a issue, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

**Comment by wilozyx** [comment]
Hey of course! You actually can just upload your datapack normally into modrinth, then click on it, and then you can simply click "package as mod" and modrinth will automatically repackage your datapack into a jar! Hope this helps :)
![Screenshot 2024-05-29 182820](https://github.com/wilozyx/Classic-Mechanics/assets/143864578/2e618b03-ec76-4de9-afa5-ef225c558f0a)

**Comment by PovarRavop** [comment]
Yes thank you. This is what you need
