### ISSUE TITLE
Silk touch Ores 

### ISSUE THREAD

**Issue by Eggnogant** [wilozyx/Classic-Mechanics#2]
I'm playing on your latest release of your data pack with MC 1.20.6, and for some reason every ore except lapis has some sort of un-toggleable silk touch effect. None of my picks have the silk touch enchant and I've checked to see if maybe I accidently toggled on the old ore drops function, and that didn't seem to be the case. I created a new world just to double check, and unfortunately, it seems that when I have the pack installed, the effect is present no matter what I do. 

Thank you for the great work on this pack! I like being able to play modern MC with features from when I was a kid.

**Comment by wilozyx** [comment]
There we go, the fix has been made! :)

You can find the new version [here](https://modrinth.com/datapack/classic-mechanics/version/EIB2PeZJ)

**Comment by Eggnogant** [comment]
Sweet! thank you so much!!
